# -----------------------------------------------------------------------------
#  File:        BasicLoopCUlib.py
#  Description: Analyzer for ntuples created by TheNtupleMaker
#  Created:     Fri Jun  3 16:38:31 2011 by mkntanalyzer.py
#  Author:      Ben Kreis
# -----------------------------------------------------------------------------
from ROOT import *
from time import sleep
from string import *
from array import array
from math import *
from sys import exit
import os, sys, re
# -----------------------------------------------------------------------------
STANDALONE = True  # set to False to work within CMSSW
if STANDALONE:
    gROOT.ProcessLine(".L treestream.cc+")
    gROOT.ProcessLine(".L pdg.cc+")
else:
    from PhysicsTools.TheNtupleMaker.AutoLoader import *
# -----------------------------------------------------------------------------
# -- Classes, procedures and functions
# -----------------------------------------------------------------------------
class outputFile:

    def __init__(self, filename, stream=None, savecount=50000):
		if stream != None:
		    print "events will be skimmed to file", filename
		    self.tree = stream.tree().CloneTree(0)
			self.weight = Double()
			self.b_weight = self.tree.Branch("eventWeight", self.weight,
											 "eventWeight/D")
			self.SAVECOUNT = savecount
		else:
			self.tree = None
			self.b_weight = None

		self.entry = 0
			
		self.filename = filename
		self.file = TFile(filename, "recreate")

		self.hist = TH1F("counts", "", 1, 0, 1)
		self.hist.SetBit(TH1.kCanRebin)
		self.hist.SetStats(0)

		self.b_weight = 0

	def addEvent(self, weight=1.0):
		if self.tree == None: return
		
		self.file = self.tree.GetCurrentFile()
		self.file.cd()
		self.tree.Fill()

		self.entry += 1		
		if self.entry % self.SAVECOUNT == 0:
			self.tree.AutoSave("SaveSelf")
				
	def count(self, cond, w=1):
		self.hist.Fill(cond, w)
		
	def close(self):
		print "==> histograms saved to file", self.filename
		if self.tree != None:			
			print "==> events skimmed to file", self.filename
			self.file = self.tree.GetCurrentFile()
			
		self.file.cd()
		#self.file.Write("", TObject.kOverwrite)
		self.file.Write()
		self.file.ls()
		self.file.Close()
# -----------------------------------------------------------------------------
class commandLine:
	def __init__(self):
		pass

def decodeCommandLine():
	argv = sys.argv
	argc = len(argv)

	cl = commandLine()
	cl.progname = split(os.path.basename(argv[0]),'.')[0]

	if argc > 1:
		cl.filelist = argv[1]
	else:
		cl.filelist = "filelist.txt"

	if argc > 2: 
		cl.outputfilename = argv[2] # 2nd (optional) command line argument
	else:
		cl.outputfilename = cl.progname + "_histograms"

	# Make sure extension is ".root"
	if cl.outputfilename[:-5] != ".root": cl.outputfilename += ".root"
	print "==> output to:", cl.outputfilename

	return cl
# -----------------------------------------------------------------------------
def error(message):
	print "** error ** " + message
	sys.exit(0)
# -----------------------------------------------------------------------------
#  Read ntuple filenames from file list

def getFilenames(filelist):
	if not os.path.exists(filelist):
		error("unable to open file: " + filelist)

	# Get ntuple file names
	filenames = filter(lambda x: x != "",
					   map(strip, open(filelist).readlines()))
	v = vector("string")()
	for filename in filenames: v.push_back(filename)
	return v
# -----------------------------------------------------------------------------
TEXTFONT = 42
TEXTSIZE = 0.031
#------------------------------------------------------------------------------
def setStyle():
	gROOT.SetStyle("Pub")
	style = gROOT.GetStyle("Pub")
	style.SetPalette(1)
	
	# For the canvas
	style.SetCanvasBorderMode(0)
	style.SetCanvasColor(kWhite)
	style.SetCanvasDefH(500)
	style.SetCanvasDefW(500)
	style.SetCanvasDefX(0)
	style.SetCanvasDefY(0)

	# For the pad
	style.SetPadBorderMode(0)
	style.SetPadColor(kWhite)
	style.SetPadGridX(kFALSE)
	style.SetPadGridY(kTRUE)
	style.SetGridColor(kGreen)
	style.SetGridStyle(3)
	style.SetGridWidth(1)

	# For the frame
	style.SetFrameBorderMode(0)
	style.SetFrameBorderSize(1)
	style.SetFrameFillColor(0)
	style.SetFrameFillStyle(0)
	style.SetFrameLineColor(1)
	style.SetFrameLineStyle(1)
	style.SetFrameLineWidth(1)

	# For the histogram
	style.SetHistLineColor(1)
	style.SetHistLineStyle(0)
	style.SetHistLineWidth(1)
	style.SetEndErrorSize(2)
	style.SetErrorX(0.)
	style.SetMarkerSize(0.1)
	style.SetMarkerStyle(20)

	# For the fit/function
	style.SetOptFit(1)
	style.SetFitFormat("5.4g")
	style.SetFuncColor(2)
	style.SetFuncStyle(1)
	style.SetFuncWidth(1)

	#For the date
	style.SetOptDate(0)

	# For the statistics box
	style.SetOptFile(0)
	style.SetOptStat("")
	# To display the mean and RMS
	#style.SetOptStat("mr") 
	style.SetStatColor(kWhite)
	style.SetStatFont(TEXTFONT)
	style.SetStatFontSize(TEXTSIZE)
	style.SetStatTextColor(1)
	style.SetStatFormat("6.4g")
	style.SetStatBorderSize(1)
	style.SetStatH(0.2)
	style.SetStatW(0.3)

	# Margins
	style.SetPadTopMargin(0.05)
	style.SetPadBottomMargin(0.16)
	style.SetPadLeftMargin(0.16)
	style.SetPadRightMargin(0.16)

	# For the global title
	style.SetOptTitle(0)
	style.SetTitleFont(TEXTFONT)
	style.SetTitleColor(1)
	style.SetTitleTextColor(1)
	style.SetTitleFillColor(10)
	style.SetTitleFontSize(TEXTSIZE*1.1)

	# For the axis titles
	style.SetTitleColor(1, "XYZ")
	style.SetTitleFont(TEXTFONT, "XYZ")
	style.SetTitleSize(TEXTSIZE*1.2, "XYZ") # 0,05
	style.SetTitleXOffset(1.25) # 0.9
	style.SetTitleYOffset(1.25) # 1.25

	# For the axis labels
	style.SetLabelColor(1, "XYZ")
	style.SetLabelFont(TEXTFONT, "XYZ")
	style.SetLabelOffset(0.006, "XYZ")
	style.SetLabelSize(TEXTSIZE*1.2, "XYZ")

	# For the axis
	style.SetAxisColor(1, "XYZ")
	style.SetStripDecimals(kTRUE)
	style.SetTickLength(0.03, "XYZ")
	style.SetNdivisions(505, "XYZ")

	# To get tick marks on the opposite side of the frame
	style.SetPadTickX(1)  
	style.SetPadTickY(1)

	# Change for log plots
	style.SetOptLogx(0)
	style.SetOptLogy(0)
	style.SetOptLogz(0)

	# Postscript options
	style.SetPaperSize(20.,20.)

	style.cd()
# -----------------------------------------------------------------------------
#  Define variables to be read
# -----------------------------------------------------------------------------
cmdline = decodeCommandLine()

#  Get names of ntuple files to be processed and open chain of ntuples

filenames = getFilenames(cmdline.filelist)
stream = itreestream(filenames, "Events")
if not stream.good(): error("unable to open ntuple file(s)")

beamspot_x0	= Double()
beamspot_y0	= Double()
beamspot_z0	= Double()
edmevent_bunchCrossing	= Double()
edmevent_event	= Double()
edmevent_isRealData	= Double()
edmevent_luminosityBlock	= Double()
edmevent_run	= Double()
edmtriggerresults_HLT_HT100U	= Double()
edmtriggerresults_HLT_HT100U_prs	= Double()
edmtriggerresults_HLT_HT120U	= Double()
edmtriggerresults_HLT_HT120U_prs	= Double()
edmtriggerresults_HLT_HT140U	= Double()
edmtriggerresults_HLT_HT140U_prs	= Double()
edmtriggerresults_HLT_HT150U_v3	= Double()
edmtriggerresults_HLT_HT150U_v3_prs	= Double()
edmtriggerresults_HLT_HT150_v1	= Double()
edmtriggerresults_HLT_HT150_v1_prs	= Double()
edmtriggerresults_HLT_HT150_v2	= Double()
edmtriggerresults_HLT_HT150_v2_prs	= Double()
edmtriggerresults_HLT_HT150_v3	= Double()
edmtriggerresults_HLT_HT150_v3_prs	= Double()
edmtriggerresults_HLT_HT250_MHT60_v2	= Double()
edmtriggerresults_HLT_HT250_MHT60_v2_prs	= Double()
edmtriggerresults_HLT_HT250_MHT60_v3	= Double()
edmtriggerresults_HLT_HT250_MHT60_v3_prs	= Double()
edmtriggerresults_HLT_HT250_v1	= Double()
edmtriggerresults_HLT_HT250_v1_prs	= Double()
edmtriggerresults_HLT_HT250_v2	= Double()
edmtriggerresults_HLT_HT250_v2_prs	= Double()
edmtriggerresults_HLT_HT250_v3	= Double()
edmtriggerresults_HLT_HT250_v3_prs	= Double()
edmtriggerresults_HLT_HT260_MHT60_v2	= Double()
edmtriggerresults_HLT_HT260_MHT60_v2_prs	= Double()
edmtriggerresults_HLT_HT300_MHT75_v2	= Double()
edmtriggerresults_HLT_HT300_MHT75_v2_prs	= Double()
edmtriggerresults_HLT_HT300_MHT75_v3	= Double()
edmtriggerresults_HLT_HT300_MHT75_v3_prs	= Double()
edmtriggerresults_HLT_HT300_MHT75_v4	= Double()
edmtriggerresults_HLT_HT300_MHT75_v4_prs	= Double()
edmtriggerresults_HLT_HT300_v1	= Double()
edmtriggerresults_HLT_HT300_v1_prs	= Double()
edmtriggerresults_HLT_HT300_v2	= Double()
edmtriggerresults_HLT_HT300_v2_prs	= Double()
edmtriggerresults_HLT_HT300_v3	= Double()
edmtriggerresults_HLT_HT300_v3_prs	= Double()
edmtriggerresults_HLT_HT300_v4	= Double()
edmtriggerresults_HLT_HT300_v4_prs	= Double()
electron1_dxywrtBeamSpot	= vector("double")(3)
electron2_caloIso	= vector("double")(9)
electron2_charge	= vector("double")(9)
electron2_chargedHadronIso	= vector("double")(9)
electron2_dB	= vector("double")(9)
electron2_deltaEtaSuperClusterTrackAtVtx	= vector("double")(9)
electron2_deltaPhiSuperClusterTrackAtVtx	= vector("double")(9)
electron2_dr03EcalRecHitSumEt	= vector("double")(9)
electron2_dr03HcalTowerSumEt	= vector("double")(9)
electron2_dr03TkSumPt	= vector("double")(9)
electron2_ecalIso	= vector("double")(9)
electron2_eidRobustTight	= vector("double")(9)
electron2_energy	= vector("double")(9)
electron2_et	= vector("double")(9)
electron2_eta	= vector("double")(9)
electron2_genLepton_eta	= vector("double")(9)
electron2_genLepton_pdgId	= vector("double")(9)
electron2_genLepton_phi	= vector("double")(9)
electron2_genLepton_pt	= vector("double")(9)
electron2_gsfTrack_d0	= vector("double")(9)
electron2_gsfTrack_trackerExpectedHitsInner_numberOfLostHits	= vector("double")(9)
electron2_hadronicOverEm	= vector("double")(9)
electron2_hcalIso	= vector("double")(9)
electron2_neutralHadronIso	= vector("double")(9)
electron2_phi	= vector("double")(9)
electron2_photonIso	= vector("double")(9)
electron2_pt	= vector("double")(9)
electron2_px	= vector("double")(9)
electron2_py	= vector("double")(9)
electron2_pz	= vector("double")(9)
electron2_sigmaIetaIeta	= vector("double")(9)
electron2_simpleEleId95relIso	= vector("double")(9)
electron2_superCluster_eta	= vector("double")(9)
electron2_trackIso	= vector("double")(9)
electron2_vz	= vector("double")(9)
electron3_caloIso	= vector("double")(3)
electron3_charge	= vector("double")(3)
electron3_chargedHadronIso	= vector("double")(3)
electron3_dB	= vector("double")(3)
electron3_deltaEtaSuperClusterTrackAtVtx	= vector("double")(3)
electron3_deltaPhiSuperClusterTrackAtVtx	= vector("double")(3)
electron3_dr03EcalRecHitSumEt	= vector("double")(3)
electron3_dr03HcalTowerSumEt	= vector("double")(3)
electron3_dr03TkSumPt	= vector("double")(3)
electron3_ecalIso	= vector("double")(3)
electron3_eidRobustTight	= vector("double")(3)
electron3_energy	= vector("double")(3)
electron3_et	= vector("double")(3)
electron3_eta	= vector("double")(3)
electron3_genLepton_eta	= vector("double")(3)
electron3_genLepton_pdgId	= vector("double")(3)
electron3_genLepton_phi	= vector("double")(3)
electron3_genLepton_pt	= vector("double")(3)
electron3_gsfTrack_d0	= vector("double")(3)
electron3_gsfTrack_trackerExpectedHitsInner_numberOfLostHits	= vector("double")(3)
electron3_hadronicOverEm	= vector("double")(3)
electron3_hcalIso	= vector("double")(3)
electron3_neutralHadronIso	= vector("double")(3)
electron3_phi	= vector("double")(3)
electron3_photonIso	= vector("double")(3)
electron3_pt	= vector("double")(3)
electron3_px	= vector("double")(3)
electron3_py	= vector("double")(3)
electron3_pz	= vector("double")(3)
electron3_sigmaIetaIeta	= vector("double")(3)
electron3_simpleEleId95relIso	= vector("double")(3)
electron3_superCluster_eta	= vector("double")(3)
electron3_trackIso	= vector("double")(3)
electron3_vz	= vector("double")(3)
electron_dxywrtBeamSpot	= vector("double")(9)
geneventinfoproduct1_pdf1	= Double()
geneventinfoproduct1_pdf2	= Double()
geneventinfoproduct1_scalePDF	= Double()
geneventinfoproduct1_weight	= Double()
geneventinfoproduct1_x1	= Double()
geneventinfoproduct1_x2	= Double()
geneventinfoproduct_pdf1	= vector("double")(91)
geneventinfoproduct_pdf2	= vector("double")(91)
geneventinfoproduct_pdfweight	= vector("double")(91)
geneventinfoproduct_pdfweightsum	= vector("double")(91)
genparticlera2_charge	= vector("double")(31)
genparticlera2_eta	= vector("double")(31)
genparticlera2_firstDaughter	= vector("double")(31)
genparticlera2_firstMother	= vector("double")(31)
genparticlera2_lastDaughter	= vector("double")(31)
genparticlera2_lastMother	= vector("double")(31)
genparticlera2_mass	= vector("double")(31)
genparticlera2_pdgId	= vector("double")(31)
genparticlera2_phi	= vector("double")(31)
genparticlera2_pt	= vector("double")(31)
genparticlera2_status	= vector("double")(31)
genruninfoproduct_externalXSecLO_error	= Double()
genruninfoproduct_externalXSecLO_value	= Double()
genruninfoproduct_filterEfficiency	= Double()
genruninfoproduct_internalXSec_error	= Double()
genruninfoproduct_internalXSec_value	= Double()
jet1_jetUncMinus	= vector("double")(175)
jet1_jetUncPlus	= vector("double")(175)
jet2_combinedSecondaryVertexBJetTags	= vector("double")(167)
jet2_combinedSecondaryVertexMVABJetTags	= vector("double")(167)
jet2_emEnergyFraction	= vector("double")(167)
jet2_energy	= vector("double")(167)
jet2_eta	= vector("double")(167)
jet2_jetBProbabilityBJetTags	= vector("double")(167)
jet2_jetID_fHPD	= vector("double")(167)
jet2_jetID_n90Hits	= vector("double")(167)
jet2_jetProbabilityBJetTags	= vector("double")(167)
jet2_partonFlavour	= vector("double")(167)
jet2_phi	= vector("double")(167)
jet2_pt	= vector("double")(167)
jet2_simpleSecondaryVertexBJetTags	= vector("double")(167)
jet2_simpleSecondaryVertexHighEffBJetTags	= vector("double")(167)
jet2_simpleSecondaryVertexHighPurBJetTags	= vector("double")(167)
jet2_softElectronByIP3dBJetTags	= vector("double")(167)
jet2_softElectronByPtBJetTags	= vector("double")(167)
jet2_softMuonBJetTags	= vector("double")(167)
jet2_softMuonByIP3dBJetTags	= vector("double")(167)
jet2_softMuonByPtBJetTags	= vector("double")(167)
jet2_trackCountingHighEffBJetTags	= vector("double")(167)
jet2_trackCountingHighPurBJetTags	= vector("double")(167)
jet2_uncor_energy	= vector("double")(167)
jet2_uncor_eta	= vector("double")(167)
jet2_uncor_phi	= vector("double")(167)
jet2_uncor_pt	= vector("double")(167)
jet3_HFHadronEnergy	= vector("double")(175)
jet3_chargedEmEnergyFraction	= vector("double")(175)
jet3_chargedHadronEnergyFraction	= vector("double")(175)
jet3_chargedMultiplicity	= vector("double")(175)
jet3_combinedSecondaryVertexBJetTags	= vector("double")(175)
jet3_combinedSecondaryVertexMVABJetTags	= vector("double")(175)
jet3_energy	= vector("double")(175)
jet3_eta	= vector("double")(175)
jet3_jetBProbabilityBJetTags	= vector("double")(175)
jet3_jetID_fHPD	= vector("double")(175)
jet3_jetID_n90Hits	= vector("double")(175)
jet3_jetProbabilityBJetTags	= vector("double")(175)
jet3_neutralEmEnergyFraction	= vector("double")(175)
jet3_neutralHadronEnergy	= vector("double")(175)
jet3_neutralHadronEnergyFraction	= vector("double")(175)
jet3_numberOfDaughters	= vector("double")(175)
jet3_partonFlavour	= vector("double")(175)
jet3_phi	= vector("double")(175)
jet3_pt	= vector("double")(175)
jet3_simpleSecondaryVertexBJetTags	= vector("double")(175)
jet3_simpleSecondaryVertexHighEffBJetTags	= vector("double")(175)
jet3_simpleSecondaryVertexHighPurBJetTags	= vector("double")(175)
jet3_softElectronByIP3dBJetTags	= vector("double")(175)
jet3_softElectronByPtBJetTags	= vector("double")(175)
jet3_softMuonBJetTags	= vector("double")(175)
jet3_softMuonByIP3dBJetTags	= vector("double")(175)
jet3_softMuonByPtBJetTags	= vector("double")(175)
jet3_trackCountingHighEffBJetTags	= vector("double")(175)
jet3_trackCountingHighPurBJetTags	= vector("double")(175)
jet3_uncor_energy	= vector("double")(175)
jet3_uncor_eta	= vector("double")(175)
jet3_uncor_phi	= vector("double")(175)
jet3_uncor_pt	= vector("double")(175)
jet_jetUncMinus	= vector("double")(167)
jet_jetUncPlus	= vector("double")(167)
met1_energy	= vector("double")(3)
met1_et	= vector("double")(3)
met1_mEtSig	= vector("double")(3)
met1_phi	= vector("double")(3)
met1_pt	= vector("double")(3)
met1_sumEt	= vector("double")(3)
met_energy	= vector("double")(3)
met_et	= vector("double")(3)
met_mEtSig	= vector("double")(3)
met_phi	= vector("double")(3)
met_pt	= vector("double")(3)
met_sumEt	= vector("double")(3)
muon1_dxywrtBeamSpot	= vector("double")(3)
muon2_AllGlobalMuons	= vector("double")(9)
muon2_GlobalMuonPromptTight	= vector("double")(9)
muon2_charge	= vector("double")(9)
muon2_chargedHadronIso	= vector("double")(9)
muon2_combinedMuon_chi2	= vector("double")(9)
muon2_combinedMuon_ndof	= vector("double")(9)
muon2_combinedMuon_numberOfValidHits	= vector("double")(9)
muon2_dB	= vector("double")(9)
muon2_ecalIso	= vector("double")(9)
muon2_energy	= vector("double")(9)
muon2_eta	= vector("double")(9)
muon2_genLepton_eta	= vector("double")(9)
muon2_genLepton_pdgId	= vector("double")(9)
muon2_genLepton_phi	= vector("double")(9)
muon2_genLepton_pt	= vector("double")(9)
muon2_globalTrack_pt	= vector("double")(9)
muon2_hcalIso	= vector("double")(9)
muon2_innerTrack_numberOfValidHits	= vector("double")(9)
muon2_innerTrack_pt	= vector("double")(9)
muon2_isGlobalMuon	= vector("double")(9)
muon2_isTrackerMuon	= vector("double")(9)
muon2_neutralHadronIso	= vector("double")(9)
muon2_phi	= vector("double")(9)
muon2_photonIso	= vector("double")(9)
muon2_pt	= vector("double")(9)
muon2_px	= vector("double")(9)
muon2_py	= vector("double")(9)
muon2_pz	= vector("double")(9)
muon2_trackIso	= vector("double")(9)
muon2_track_d0	= vector("double")(9)
muon2_track_hitPattern_numberOfValidMuonHits	= vector("double")(9)
muon2_track_hitPattern_numberOfValidPixelHits	= vector("double")(9)
muon2_track_normalizedChi2	= vector("double")(9)
muon2_vz	= vector("double")(9)
muon3_AllGlobalMuons	= vector("double")(3)
muon3_GlobalMuonPromptTight	= vector("double")(3)
muon3_charge	= vector("double")(3)
muon3_chargedHadronIso	= vector("double")(3)
muon3_combinedMuon_chi2	= vector("double")(3)
muon3_combinedMuon_ndof	= vector("double")(3)
muon3_combinedMuon_numberOfValidHits	= vector("double")(3)
muon3_dB	= vector("double")(3)
muon3_ecalIso	= vector("double")(3)
muon3_energy	= vector("double")(3)
muon3_eta	= vector("double")(3)
muon3_genLepton_eta	= vector("double")(3)
muon3_genLepton_pdgId	= vector("double")(3)
muon3_genLepton_phi	= vector("double")(3)
muon3_genLepton_pt	= vector("double")(3)
muon3_globalTrack_pt	= vector("double")(3)
muon3_hcalIso	= vector("double")(3)
muon3_innerTrack_numberOfValidHits	= vector("double")(3)
muon3_innerTrack_pt	= vector("double")(3)
muon3_isGlobalMuon	= vector("double")(3)
muon3_isTrackerMuon	= vector("double")(3)
muon3_neutralHadronIso	= vector("double")(3)
muon3_phi	= vector("double")(3)
muon3_photonIso	= vector("double")(3)
muon3_pt	= vector("double")(3)
muon3_px	= vector("double")(3)
muon3_py	= vector("double")(3)
muon3_pz	= vector("double")(3)
muon3_trackIso	= vector("double")(3)
muon3_track_d0	= vector("double")(3)
muon3_track_hitPattern_numberOfValidMuonHits	= vector("double")(3)
muon3_track_hitPattern_numberOfValidPixelHits	= vector("double")(3)
muon3_track_normalizedChi2	= vector("double")(3)
muon3_vz	= vector("double")(3)
muon_dxywrtBeamSpot	= vector("double")(9)
nGenEventInfoProductHelper_generator	= Long()
nelectron	= Long()
nelectron1	= Long()
nelectron2	= Long()
nelectron3	= Long()
ngenparticlera2b	= Long()
njet	= Long()
njet1	= Long()
njet2	= Long()
njet3	= Long()
nmet	= Long()
nmet1	= Long()
nmuon	= Long()
nmuon1	= Long()
nmuon2	= Long()
nmuon3	= Long()
ntau	= Long()
ntau1	= Long()
nvertex	= Long()
tau1_caloIso	= vector("double")(9)
tau1_ecalIso	= vector("double")(9)
tau1_energy	= vector("double")(9)
tau1_et	= vector("double")(9)
tau1_eta	= vector("double")(9)
tau1_hcalIso	= vector("double")(9)
tau1_phi	= vector("double")(9)
tau1_pt	= vector("double")(9)
tau1_px	= vector("double")(9)
tau1_py	= vector("double")(9)
tau1_pz	= vector("double")(9)
tau1_tauID_againstElectron	= vector("double")(9)
tau1_tauID_againstMuon	= vector("double")(9)
tau1_tauID_byIsolation	= vector("double")(9)
tau1_tauID_byTaNC	= vector("double")(9)
tau1_tauID_byTaNCfrHalfPercent	= vector("double")(9)
tau1_tauID_byTaNCfrQuarterPercent	= vector("double")(9)
tau1_trackIso	= vector("double")(9)
tau_genTauDecayModeID	= vector("double")(9)
vertex_isFake	= vector("double")(39)
vertex_isValid	= vector("double")(39)
vertex_ndof	= vector("double")(39)
vertex_normalizedChi2	= vector("double")(39)
vertex_position_Rho	= vector("double")(39)
vertex_tracksSize	= vector("double")(39)
vertex_x	= vector("double")(39)
vertex_xError	= vector("double")(39)
vertex_y	= vector("double")(39)
vertex_yError	= vector("double")(39)
vertex_z	= vector("double")(39)
vertex_zError	= vector("double")(39)

stream.select("recoBeamSpot_offlineBeamSpot.x0", beamspot_x0)
stream.select("recoBeamSpot_offlineBeamSpot.y0", beamspot_y0)
stream.select("recoBeamSpot_offlineBeamSpot.z0", beamspot_z0)
stream.select("edmEventHelper_info.bunchCrossing", edmevent_bunchCrossing)
stream.select("edmEventHelper_info.event", edmevent_event)
stream.select("edmEventHelper_info.isRealData", edmevent_isRealData)
stream.select("edmEventHelper_info.luminosityBlock", edmevent_luminosityBlock)
stream.select("edmEventHelper_info.run", edmevent_run)
stream.select("edmTriggerResultsHelper_TriggerResults.HLT_HT100U", edmtriggerresults_HLT_HT100U)
stream.select("edmTriggerResultsHelper_TriggerResults.HLT_HT100U_prs", edmtriggerresults_HLT_HT100U_prs)
stream.select("edmTriggerResultsHelper_TriggerResults.HLT_HT120U", edmtriggerresults_HLT_HT120U)
stream.select("edmTriggerResultsHelper_TriggerResults.HLT_HT120U_prs", edmtriggerresults_HLT_HT120U_prs)
stream.select("edmTriggerResultsHelper_TriggerResults.HLT_HT140U", edmtriggerresults_HLT_HT140U)
stream.select("edmTriggerResultsHelper_TriggerResults.HLT_HT140U_prs", edmtriggerresults_HLT_HT140U_prs)
stream.select("edmTriggerResultsHelper_TriggerResults.HLT_HT150U_v3", edmtriggerresults_HLT_HT150U_v3)
stream.select("edmTriggerResultsHelper_TriggerResults.HLT_HT150U_v3_prs", edmtriggerresults_HLT_HT150U_v3_prs)
stream.select("edmTriggerResultsHelper_TriggerResults.HLT_HT150_v1", edmtriggerresults_HLT_HT150_v1)
stream.select("edmTriggerResultsHelper_TriggerResults.HLT_HT150_v1_prs", edmtriggerresults_HLT_HT150_v1_prs)
stream.select("edmTriggerResultsHelper_TriggerResults.HLT_HT150_v2", edmtriggerresults_HLT_HT150_v2)
stream.select("edmTriggerResultsHelper_TriggerResults.HLT_HT150_v2_prs", edmtriggerresults_HLT_HT150_v2_prs)
stream.select("edmTriggerResultsHelper_TriggerResults.HLT_HT150_v3", edmtriggerresults_HLT_HT150_v3)
stream.select("edmTriggerResultsHelper_TriggerResults.HLT_HT150_v3_prs", edmtriggerresults_HLT_HT150_v3_prs)
stream.select("edmTriggerResultsHelper_TriggerResults.HLT_HT250_MHT60_v2", edmtriggerresults_HLT_HT250_MHT60_v2)
stream.select("edmTriggerResultsHelper_TriggerResults.HLT_HT250_MHT60_v2_prs", edmtriggerresults_HLT_HT250_MHT60_v2_prs)
stream.select("edmTriggerResultsHelper_TriggerResults.HLT_HT250_MHT60_v3", edmtriggerresults_HLT_HT250_MHT60_v3)
stream.select("edmTriggerResultsHelper_TriggerResults.HLT_HT250_MHT60_v3_prs", edmtriggerresults_HLT_HT250_MHT60_v3_prs)
stream.select("edmTriggerResultsHelper_TriggerResults.HLT_HT250_v1", edmtriggerresults_HLT_HT250_v1)
stream.select("edmTriggerResultsHelper_TriggerResults.HLT_HT250_v1_prs", edmtriggerresults_HLT_HT250_v1_prs)
stream.select("edmTriggerResultsHelper_TriggerResults.HLT_HT250_v2", edmtriggerresults_HLT_HT250_v2)
stream.select("edmTriggerResultsHelper_TriggerResults.HLT_HT250_v2_prs", edmtriggerresults_HLT_HT250_v2_prs)
stream.select("edmTriggerResultsHelper_TriggerResults.HLT_HT250_v3", edmtriggerresults_HLT_HT250_v3)
stream.select("edmTriggerResultsHelper_TriggerResults.HLT_HT250_v3_prs", edmtriggerresults_HLT_HT250_v3_prs)
stream.select("edmTriggerResultsHelper_TriggerResults.HLT_HT260_MHT60_v2", edmtriggerresults_HLT_HT260_MHT60_v2)
stream.select("edmTriggerResultsHelper_TriggerResults.HLT_HT260_MHT60_v2_prs", edmtriggerresults_HLT_HT260_MHT60_v2_prs)
stream.select("edmTriggerResultsHelper_TriggerResults.HLT_HT300_MHT75_v2", edmtriggerresults_HLT_HT300_MHT75_v2)
stream.select("edmTriggerResultsHelper_TriggerResults.HLT_HT300_MHT75_v2_prs", edmtriggerresults_HLT_HT300_MHT75_v2_prs)
stream.select("edmTriggerResultsHelper_TriggerResults.HLT_HT300_MHT75_v3", edmtriggerresults_HLT_HT300_MHT75_v3)
stream.select("edmTriggerResultsHelper_TriggerResults.HLT_HT300_MHT75_v3_prs", edmtriggerresults_HLT_HT300_MHT75_v3_prs)
stream.select("edmTriggerResultsHelper_TriggerResults.HLT_HT300_MHT75_v4", edmtriggerresults_HLT_HT300_MHT75_v4)
stream.select("edmTriggerResultsHelper_TriggerResults.HLT_HT300_MHT75_v4_prs", edmtriggerresults_HLT_HT300_MHT75_v4_prs)
stream.select("edmTriggerResultsHelper_TriggerResults.HLT_HT300_v1", edmtriggerresults_HLT_HT300_v1)
stream.select("edmTriggerResultsHelper_TriggerResults.HLT_HT300_v1_prs", edmtriggerresults_HLT_HT300_v1_prs)
stream.select("edmTriggerResultsHelper_TriggerResults.HLT_HT300_v2", edmtriggerresults_HLT_HT300_v2)
stream.select("edmTriggerResultsHelper_TriggerResults.HLT_HT300_v2_prs", edmtriggerresults_HLT_HT300_v2_prs)
stream.select("edmTriggerResultsHelper_TriggerResults.HLT_HT300_v3", edmtriggerresults_HLT_HT300_v3)
stream.select("edmTriggerResultsHelper_TriggerResults.HLT_HT300_v3_prs", edmtriggerresults_HLT_HT300_v3_prs)
stream.select("edmTriggerResultsHelper_TriggerResults.HLT_HT300_v4", edmtriggerresults_HLT_HT300_v4)
stream.select("edmTriggerResultsHelper_TriggerResults.HLT_HT300_v4_prs", edmtriggerresults_HLT_HT300_v4_prs)
stream.select("patElectronHelper_selectedPatElectronsPF.dxywrtBeamSpot", electron1_dxywrtBeamSpot)
stream.select("patElectron_patElectronsNoIsoPF.caloIso", electron2_caloIso)
stream.select("patElectron_patElectronsNoIsoPF.charge", electron2_charge)
stream.select("patElectron_patElectronsNoIsoPF.chargedHadronIso", electron2_chargedHadronIso)
stream.select("patElectron_patElectronsNoIsoPF.dB", electron2_dB)
stream.select("patElectron_patElectronsNoIsoPF.deltaEtaSuperClusterTrackAtVtx", electron2_deltaEtaSuperClusterTrackAtVtx)
stream.select("patElectron_patElectronsNoIsoPF.deltaPhiSuperClusterTrackAtVtx", electron2_deltaPhiSuperClusterTrackAtVtx)
stream.select("patElectron_patElectronsNoIsoPF.dr03EcalRecHitSumEt", electron2_dr03EcalRecHitSumEt)
stream.select("patElectron_patElectronsNoIsoPF.dr03HcalTowerSumEt", electron2_dr03HcalTowerSumEt)
stream.select("patElectron_patElectronsNoIsoPF.dr03TkSumPt", electron2_dr03TkSumPt)
stream.select("patElectron_patElectronsNoIsoPF.ecalIso", electron2_ecalIso)
stream.select("patElectron_patElectronsNoIsoPF.eidRobustTight", electron2_eidRobustTight)
stream.select("patElectron_patElectronsNoIsoPF.energy", electron2_energy)
stream.select("patElectron_patElectronsNoIsoPF.et", electron2_et)
stream.select("patElectron_patElectronsNoIsoPF.eta", electron2_eta)
stream.select("patElectron_patElectronsNoIsoPF.genLepton_eta", electron2_genLepton_eta)
stream.select("patElectron_patElectronsNoIsoPF.genLepton_pdgId", electron2_genLepton_pdgId)
stream.select("patElectron_patElectronsNoIsoPF.genLepton_phi", electron2_genLepton_phi)
stream.select("patElectron_patElectronsNoIsoPF.genLepton_pt", electron2_genLepton_pt)
stream.select("patElectron_patElectronsNoIsoPF.gsfTrack_d0", electron2_gsfTrack_d0)
stream.select("patElectron_patElectronsNoIsoPF.gsfTrack_trackerExpectedHitsInner_numberOfLostHits", electron2_gsfTrack_trackerExpectedHitsInner_numberOfLostHits)
stream.select("patElectron_patElectronsNoIsoPF.hadronicOverEm", electron2_hadronicOverEm)
stream.select("patElectron_patElectronsNoIsoPF.hcalIso", electron2_hcalIso)
stream.select("patElectron_patElectronsNoIsoPF.neutralHadronIso", electron2_neutralHadronIso)
stream.select("patElectron_patElectronsNoIsoPF.phi", electron2_phi)
stream.select("patElectron_patElectronsNoIsoPF.photonIso", electron2_photonIso)
stream.select("patElectron_patElectronsNoIsoPF.pt", electron2_pt)
stream.select("patElectron_patElectronsNoIsoPF.px", electron2_px)
stream.select("patElectron_patElectronsNoIsoPF.py", electron2_py)
stream.select("patElectron_patElectronsNoIsoPF.pz", electron2_pz)
stream.select("patElectron_patElectronsNoIsoPF.sigmaIetaIeta", electron2_sigmaIetaIeta)
stream.select("patElectron_patElectronsNoIsoPF.simpleEleId95relIso", electron2_simpleEleId95relIso)
stream.select("patElectron_patElectronsNoIsoPF.superCluster_eta", electron2_superCluster_eta)
stream.select("patElectron_patElectronsNoIsoPF.trackIso", electron2_trackIso)
stream.select("patElectron_patElectronsNoIsoPF.vz", electron2_vz)
stream.select("patElectron_selectedPatElectronsPF.caloIso", electron3_caloIso)
stream.select("patElectron_selectedPatElectronsPF.charge", electron3_charge)
stream.select("patElectron_selectedPatElectronsPF.chargedHadronIso", electron3_chargedHadronIso)
stream.select("patElectron_selectedPatElectronsPF.dB", electron3_dB)
stream.select("patElectron_selectedPatElectronsPF.deltaEtaSuperClusterTrackAtVtx", electron3_deltaEtaSuperClusterTrackAtVtx)
stream.select("patElectron_selectedPatElectronsPF.deltaPhiSuperClusterTrackAtVtx", electron3_deltaPhiSuperClusterTrackAtVtx)
stream.select("patElectron_selectedPatElectronsPF.dr03EcalRecHitSumEt", electron3_dr03EcalRecHitSumEt)
stream.select("patElectron_selectedPatElectronsPF.dr03HcalTowerSumEt", electron3_dr03HcalTowerSumEt)
stream.select("patElectron_selectedPatElectronsPF.dr03TkSumPt", electron3_dr03TkSumPt)
stream.select("patElectron_selectedPatElectronsPF.ecalIso", electron3_ecalIso)
stream.select("patElectron_selectedPatElectronsPF.eidRobustTight", electron3_eidRobustTight)
stream.select("patElectron_selectedPatElectronsPF.energy", electron3_energy)
stream.select("patElectron_selectedPatElectronsPF.et", electron3_et)
stream.select("patElectron_selectedPatElectronsPF.eta", electron3_eta)
stream.select("patElectron_selectedPatElectronsPF.genLepton_eta", electron3_genLepton_eta)
stream.select("patElectron_selectedPatElectronsPF.genLepton_pdgId", electron3_genLepton_pdgId)
stream.select("patElectron_selectedPatElectronsPF.genLepton_phi", electron3_genLepton_phi)
stream.select("patElectron_selectedPatElectronsPF.genLepton_pt", electron3_genLepton_pt)
stream.select("patElectron_selectedPatElectronsPF.gsfTrack_d0", electron3_gsfTrack_d0)
stream.select("patElectron_selectedPatElectronsPF.gsfTrack_trackerExpectedHitsInner_numberOfLostHits", electron3_gsfTrack_trackerExpectedHitsInner_numberOfLostHits)
stream.select("patElectron_selectedPatElectronsPF.hadronicOverEm", electron3_hadronicOverEm)
stream.select("patElectron_selectedPatElectronsPF.hcalIso", electron3_hcalIso)
stream.select("patElectron_selectedPatElectronsPF.neutralHadronIso", electron3_neutralHadronIso)
stream.select("patElectron_selectedPatElectronsPF.phi", electron3_phi)
stream.select("patElectron_selectedPatElectronsPF.photonIso", electron3_photonIso)
stream.select("patElectron_selectedPatElectronsPF.pt", electron3_pt)
stream.select("patElectron_selectedPatElectronsPF.px", electron3_px)
stream.select("patElectron_selectedPatElectronsPF.py", electron3_py)
stream.select("patElectron_selectedPatElectronsPF.pz", electron3_pz)
stream.select("patElectron_selectedPatElectronsPF.sigmaIetaIeta", electron3_sigmaIetaIeta)
stream.select("patElectron_selectedPatElectronsPF.simpleEleId95relIso", electron3_simpleEleId95relIso)
stream.select("patElectron_selectedPatElectronsPF.superCluster_eta", electron3_superCluster_eta)
stream.select("patElectron_selectedPatElectronsPF.trackIso", electron3_trackIso)
stream.select("patElectron_selectedPatElectronsPF.vz", electron3_vz)
stream.select("patElectronHelper_patElectronsNoIsoPF.dxywrtBeamSpot", electron_dxywrtBeamSpot)
stream.select("GenEventInfoProduct_generator.pdf1", geneventinfoproduct1_pdf1)
stream.select("GenEventInfoProduct_generator.pdf2", geneventinfoproduct1_pdf2)
stream.select("GenEventInfoProduct_generator.scalePDF", geneventinfoproduct1_scalePDF)
stream.select("GenEventInfoProduct_generator.weight", geneventinfoproduct1_weight)
stream.select("GenEventInfoProduct_generator.x1", geneventinfoproduct1_x1)
stream.select("GenEventInfoProduct_generator.x2", geneventinfoproduct1_x2)
stream.select("GenEventInfoProductHelper_generator.pdf1", geneventinfoproduct_pdf1)
stream.select("GenEventInfoProductHelper_generator.pdf2", geneventinfoproduct_pdf2)
stream.select("GenEventInfoProductHelper_generator.pdfweight", geneventinfoproduct_pdfweight)
stream.select("GenEventInfoProductHelper_generator.pdfweightsum", geneventinfoproduct_pdfweightsum)
stream.select("recoGenParticleHelperRA2b_genParticles.charge", genparticlera2_charge)
stream.select("recoGenParticleHelperRA2b_genParticles.eta", genparticlera2_eta)
stream.select("recoGenParticleHelperRA2b_genParticles.firstDaughter", genparticlera2_firstDaughter)
stream.select("recoGenParticleHelperRA2b_genParticles.firstMother", genparticlera2_firstMother)
stream.select("recoGenParticleHelperRA2b_genParticles.lastDaughter", genparticlera2_lastDaughter)
stream.select("recoGenParticleHelperRA2b_genParticles.lastMother", genparticlera2_lastMother)
stream.select("recoGenParticleHelperRA2b_genParticles.mass", genparticlera2_mass)
stream.select("recoGenParticleHelperRA2b_genParticles.pdgId", genparticlera2_pdgId)
stream.select("recoGenParticleHelperRA2b_genParticles.phi", genparticlera2_phi)
stream.select("recoGenParticleHelperRA2b_genParticles.pt", genparticlera2_pt)
stream.select("recoGenParticleHelperRA2b_genParticles.status", genparticlera2_status)
stream.select("GenRunInfoProduct_generator.externalXSecLO_error", genruninfoproduct_externalXSecLO_error)
stream.select("GenRunInfoProduct_generator.externalXSecLO_value", genruninfoproduct_externalXSecLO_value)
stream.select("GenRunInfoProduct_generator.filterEfficiency", genruninfoproduct_filterEfficiency)
stream.select("GenRunInfoProduct_generator.internalXSec_error", genruninfoproduct_internalXSec_error)
stream.select("GenRunInfoProduct_generator.internalXSec_value", genruninfoproduct_internalXSec_value)
stream.select("patJetHelper_selectedPatJetsPF.jetUncMinus", jet1_jetUncMinus)
stream.select("patJetHelper_selectedPatJetsPF.jetUncPlus", jet1_jetUncPlus)
stream.select("patJet_cleanPatJetsAK5Calo.combinedSecondaryVertexBJetTags", jet2_combinedSecondaryVertexBJetTags)
stream.select("patJet_cleanPatJetsAK5Calo.combinedSecondaryVertexMVABJetTags", jet2_combinedSecondaryVertexMVABJetTags)
stream.select("patJet_cleanPatJetsAK5Calo.emEnergyFraction", jet2_emEnergyFraction)
stream.select("patJet_cleanPatJetsAK5Calo.energy", jet2_energy)
stream.select("patJet_cleanPatJetsAK5Calo.eta", jet2_eta)
stream.select("patJet_cleanPatJetsAK5Calo.jetBProbabilityBJetTags", jet2_jetBProbabilityBJetTags)
stream.select("patJet_cleanPatJetsAK5Calo.jetID_fHPD", jet2_jetID_fHPD)
stream.select("patJet_cleanPatJetsAK5Calo.jetID_n90Hits", jet2_jetID_n90Hits)
stream.select("patJet_cleanPatJetsAK5Calo.jetProbabilityBJetTags", jet2_jetProbabilityBJetTags)
stream.select("patJet_cleanPatJetsAK5Calo.partonFlavour", jet2_partonFlavour)
stream.select("patJet_cleanPatJetsAK5Calo.phi", jet2_phi)
stream.select("patJet_cleanPatJetsAK5Calo.pt", jet2_pt)
stream.select("patJet_cleanPatJetsAK5Calo.simpleSecondaryVertexBJetTags", jet2_simpleSecondaryVertexBJetTags)
stream.select("patJet_cleanPatJetsAK5Calo.simpleSecondaryVertexHighEffBJetTags", jet2_simpleSecondaryVertexHighEffBJetTags)
stream.select("patJet_cleanPatJetsAK5Calo.simpleSecondaryVertexHighPurBJetTags", jet2_simpleSecondaryVertexHighPurBJetTags)
stream.select("patJet_cleanPatJetsAK5Calo.softElectronByIP3dBJetTags", jet2_softElectronByIP3dBJetTags)
stream.select("patJet_cleanPatJetsAK5Calo.softElectronByPtBJetTags", jet2_softElectronByPtBJetTags)
stream.select("patJet_cleanPatJetsAK5Calo.softMuonBJetTags", jet2_softMuonBJetTags)
stream.select("patJet_cleanPatJetsAK5Calo.softMuonByIP3dBJetTags", jet2_softMuonByIP3dBJetTags)
stream.select("patJet_cleanPatJetsAK5Calo.softMuonByPtBJetTags", jet2_softMuonByPtBJetTags)
stream.select("patJet_cleanPatJetsAK5Calo.trackCountingHighEffBJetTags", jet2_trackCountingHighEffBJetTags)
stream.select("patJet_cleanPatJetsAK5Calo.trackCountingHighPurBJetTags", jet2_trackCountingHighPurBJetTags)
stream.select("patJet_cleanPatJetsAK5Calo.uncor_energy", jet2_uncor_energy)
stream.select("patJet_cleanPatJetsAK5Calo.uncor_eta", jet2_uncor_eta)
stream.select("patJet_cleanPatJetsAK5Calo.uncor_phi", jet2_uncor_phi)
stream.select("patJet_cleanPatJetsAK5Calo.uncor_pt", jet2_uncor_pt)
stream.select("patJet_selectedPatJetsPF.HFHadronEnergy", jet3_HFHadronEnergy)
stream.select("patJet_selectedPatJetsPF.chargedEmEnergyFraction", jet3_chargedEmEnergyFraction)
stream.select("patJet_selectedPatJetsPF.chargedHadronEnergyFraction", jet3_chargedHadronEnergyFraction)
stream.select("patJet_selectedPatJetsPF.chargedMultiplicity", jet3_chargedMultiplicity)
stream.select("patJet_selectedPatJetsPF.combinedSecondaryVertexBJetTags", jet3_combinedSecondaryVertexBJetTags)
stream.select("patJet_selectedPatJetsPF.combinedSecondaryVertexMVABJetTags", jet3_combinedSecondaryVertexMVABJetTags)
stream.select("patJet_selectedPatJetsPF.energy", jet3_energy)
stream.select("patJet_selectedPatJetsPF.eta", jet3_eta)
stream.select("patJet_selectedPatJetsPF.jetBProbabilityBJetTags", jet3_jetBProbabilityBJetTags)
stream.select("patJet_selectedPatJetsPF.jetID_fHPD", jet3_jetID_fHPD)
stream.select("patJet_selectedPatJetsPF.jetID_n90Hits", jet3_jetID_n90Hits)
stream.select("patJet_selectedPatJetsPF.jetProbabilityBJetTags", jet3_jetProbabilityBJetTags)
stream.select("patJet_selectedPatJetsPF.neutralEmEnergyFraction", jet3_neutralEmEnergyFraction)
stream.select("patJet_selectedPatJetsPF.neutralHadronEnergy", jet3_neutralHadronEnergy)
stream.select("patJet_selectedPatJetsPF.neutralHadronEnergyFraction", jet3_neutralHadronEnergyFraction)
stream.select("patJet_selectedPatJetsPF.numberOfDaughters", jet3_numberOfDaughters)
stream.select("patJet_selectedPatJetsPF.partonFlavour", jet3_partonFlavour)
stream.select("patJet_selectedPatJetsPF.phi", jet3_phi)
stream.select("patJet_selectedPatJetsPF.pt", jet3_pt)
stream.select("patJet_selectedPatJetsPF.simpleSecondaryVertexBJetTags", jet3_simpleSecondaryVertexBJetTags)
stream.select("patJet_selectedPatJetsPF.simpleSecondaryVertexHighEffBJetTags", jet3_simpleSecondaryVertexHighEffBJetTags)
stream.select("patJet_selectedPatJetsPF.simpleSecondaryVertexHighPurBJetTags", jet3_simpleSecondaryVertexHighPurBJetTags)
stream.select("patJet_selectedPatJetsPF.softElectronByIP3dBJetTags", jet3_softElectronByIP3dBJetTags)
stream.select("patJet_selectedPatJetsPF.softElectronByPtBJetTags", jet3_softElectronByPtBJetTags)
stream.select("patJet_selectedPatJetsPF.softMuonBJetTags", jet3_softMuonBJetTags)
stream.select("patJet_selectedPatJetsPF.softMuonByIP3dBJetTags", jet3_softMuonByIP3dBJetTags)
stream.select("patJet_selectedPatJetsPF.softMuonByPtBJetTags", jet3_softMuonByPtBJetTags)
stream.select("patJet_selectedPatJetsPF.trackCountingHighEffBJetTags", jet3_trackCountingHighEffBJetTags)
stream.select("patJet_selectedPatJetsPF.trackCountingHighPurBJetTags", jet3_trackCountingHighPurBJetTags)
stream.select("patJet_selectedPatJetsPF.uncor_energy", jet3_uncor_energy)
stream.select("patJet_selectedPatJetsPF.uncor_eta", jet3_uncor_eta)
stream.select("patJet_selectedPatJetsPF.uncor_phi", jet3_uncor_phi)
stream.select("patJet_selectedPatJetsPF.uncor_pt", jet3_uncor_pt)
stream.select("patJetHelper_cleanPatJetsAK5Calo.jetUncMinus", jet_jetUncMinus)
stream.select("patJetHelper_cleanPatJetsAK5Calo.jetUncPlus", jet_jetUncPlus)
stream.select("patMET_patMETsPF.energy", met1_energy)
stream.select("patMET_patMETsPF.et", met1_et)
stream.select("patMET_patMETsPF.mEtSig", met1_mEtSig)
stream.select("patMET_patMETsPF.phi", met1_phi)
stream.select("patMET_patMETsPF.pt", met1_pt)
stream.select("patMET_patMETsPF.sumEt", met1_sumEt)
stream.select("patMET_patMETsAK5Calo.energy", met_energy)
stream.select("patMET_patMETsAK5Calo.et", met_et)
stream.select("patMET_patMETsAK5Calo.mEtSig", met_mEtSig)
stream.select("patMET_patMETsAK5Calo.phi", met_phi)
stream.select("patMET_patMETsAK5Calo.pt", met_pt)
stream.select("patMET_patMETsAK5Calo.sumEt", met_sumEt)
stream.select("patMuonHelper_selectedPatMuonsPF.dxywrtBeamSpot", muon1_dxywrtBeamSpot)
stream.select("patMuon_patMuonsNoIsoPF.AllGlobalMuons", muon2_AllGlobalMuons)
stream.select("patMuon_patMuonsNoIsoPF.GlobalMuonPromptTight", muon2_GlobalMuonPromptTight)
stream.select("patMuon_patMuonsNoIsoPF.charge", muon2_charge)
stream.select("patMuon_patMuonsNoIsoPF.chargedHadronIso", muon2_chargedHadronIso)
stream.select("patMuon_patMuonsNoIsoPF.combinedMuon_chi2", muon2_combinedMuon_chi2)
stream.select("patMuon_patMuonsNoIsoPF.combinedMuon_ndof", muon2_combinedMuon_ndof)
stream.select("patMuon_patMuonsNoIsoPF.combinedMuon_numberOfValidHits", muon2_combinedMuon_numberOfValidHits)
stream.select("patMuon_patMuonsNoIsoPF.dB", muon2_dB)
stream.select("patMuon_patMuonsNoIsoPF.ecalIso", muon2_ecalIso)
stream.select("patMuon_patMuonsNoIsoPF.energy", muon2_energy)
stream.select("patMuon_patMuonsNoIsoPF.eta", muon2_eta)
stream.select("patMuon_patMuonsNoIsoPF.genLepton_eta", muon2_genLepton_eta)
stream.select("patMuon_patMuonsNoIsoPF.genLepton_pdgId", muon2_genLepton_pdgId)
stream.select("patMuon_patMuonsNoIsoPF.genLepton_phi", muon2_genLepton_phi)
stream.select("patMuon_patMuonsNoIsoPF.genLepton_pt", muon2_genLepton_pt)
stream.select("patMuon_patMuonsNoIsoPF.globalTrack_pt", muon2_globalTrack_pt)
stream.select("patMuon_patMuonsNoIsoPF.hcalIso", muon2_hcalIso)
stream.select("patMuon_patMuonsNoIsoPF.innerTrack_numberOfValidHits", muon2_innerTrack_numberOfValidHits)
stream.select("patMuon_patMuonsNoIsoPF.innerTrack_pt", muon2_innerTrack_pt)
stream.select("patMuon_patMuonsNoIsoPF.isGlobalMuon", muon2_isGlobalMuon)
stream.select("patMuon_patMuonsNoIsoPF.isTrackerMuon", muon2_isTrackerMuon)
stream.select("patMuon_patMuonsNoIsoPF.neutralHadronIso", muon2_neutralHadronIso)
stream.select("patMuon_patMuonsNoIsoPF.phi", muon2_phi)
stream.select("patMuon_patMuonsNoIsoPF.photonIso", muon2_photonIso)
stream.select("patMuon_patMuonsNoIsoPF.pt", muon2_pt)
stream.select("patMuon_patMuonsNoIsoPF.px", muon2_px)
stream.select("patMuon_patMuonsNoIsoPF.py", muon2_py)
stream.select("patMuon_patMuonsNoIsoPF.pz", muon2_pz)
stream.select("patMuon_patMuonsNoIsoPF.trackIso", muon2_trackIso)
stream.select("patMuon_patMuonsNoIsoPF.track_d0", muon2_track_d0)
stream.select("patMuon_patMuonsNoIsoPF.track_hitPattern_numberOfValidMuonHits", muon2_track_hitPattern_numberOfValidMuonHits)
stream.select("patMuon_patMuonsNoIsoPF.track_hitPattern_numberOfValidPixelHits", muon2_track_hitPattern_numberOfValidPixelHits)
stream.select("patMuon_patMuonsNoIsoPF.track_normalizedChi2", muon2_track_normalizedChi2)
stream.select("patMuon_patMuonsNoIsoPF.vz", muon2_vz)
stream.select("patMuon_selectedPatMuonsPF.AllGlobalMuons", muon3_AllGlobalMuons)
stream.select("patMuon_selectedPatMuonsPF.GlobalMuonPromptTight", muon3_GlobalMuonPromptTight)
stream.select("patMuon_selectedPatMuonsPF.charge", muon3_charge)
stream.select("patMuon_selectedPatMuonsPF.chargedHadronIso", muon3_chargedHadronIso)
stream.select("patMuon_selectedPatMuonsPF.combinedMuon_chi2", muon3_combinedMuon_chi2)
stream.select("patMuon_selectedPatMuonsPF.combinedMuon_ndof", muon3_combinedMuon_ndof)
stream.select("patMuon_selectedPatMuonsPF.combinedMuon_numberOfValidHits", muon3_combinedMuon_numberOfValidHits)
stream.select("patMuon_selectedPatMuonsPF.dB", muon3_dB)
stream.select("patMuon_selectedPatMuonsPF.ecalIso", muon3_ecalIso)
stream.select("patMuon_selectedPatMuonsPF.energy", muon3_energy)
stream.select("patMuon_selectedPatMuonsPF.eta", muon3_eta)
stream.select("patMuon_selectedPatMuonsPF.genLepton_eta", muon3_genLepton_eta)
stream.select("patMuon_selectedPatMuonsPF.genLepton_pdgId", muon3_genLepton_pdgId)
stream.select("patMuon_selectedPatMuonsPF.genLepton_phi", muon3_genLepton_phi)
stream.select("patMuon_selectedPatMuonsPF.genLepton_pt", muon3_genLepton_pt)
stream.select("patMuon_selectedPatMuonsPF.globalTrack_pt", muon3_globalTrack_pt)
stream.select("patMuon_selectedPatMuonsPF.hcalIso", muon3_hcalIso)
stream.select("patMuon_selectedPatMuonsPF.innerTrack_numberOfValidHits", muon3_innerTrack_numberOfValidHits)
stream.select("patMuon_selectedPatMuonsPF.innerTrack_pt", muon3_innerTrack_pt)
stream.select("patMuon_selectedPatMuonsPF.isGlobalMuon", muon3_isGlobalMuon)
stream.select("patMuon_selectedPatMuonsPF.isTrackerMuon", muon3_isTrackerMuon)
stream.select("patMuon_selectedPatMuonsPF.neutralHadronIso", muon3_neutralHadronIso)
stream.select("patMuon_selectedPatMuonsPF.phi", muon3_phi)
stream.select("patMuon_selectedPatMuonsPF.photonIso", muon3_photonIso)
stream.select("patMuon_selectedPatMuonsPF.pt", muon3_pt)
stream.select("patMuon_selectedPatMuonsPF.px", muon3_px)
stream.select("patMuon_selectedPatMuonsPF.py", muon3_py)
stream.select("patMuon_selectedPatMuonsPF.pz", muon3_pz)
stream.select("patMuon_selectedPatMuonsPF.trackIso", muon3_trackIso)
stream.select("patMuon_selectedPatMuonsPF.track_d0", muon3_track_d0)
stream.select("patMuon_selectedPatMuonsPF.track_hitPattern_numberOfValidMuonHits", muon3_track_hitPattern_numberOfValidMuonHits)
stream.select("patMuon_selectedPatMuonsPF.track_hitPattern_numberOfValidPixelHits", muon3_track_hitPattern_numberOfValidPixelHits)
stream.select("patMuon_selectedPatMuonsPF.track_normalizedChi2", muon3_track_normalizedChi2)
stream.select("patMuon_selectedPatMuonsPF.vz", muon3_vz)
stream.select("patMuonHelper_patMuonsNoIsoPF.dxywrtBeamSpot", muon_dxywrtBeamSpot)
stream.select("nGenEventInfoProductHelper_generator", nGenEventInfoProductHelper_generator)
stream.select("npatElectronHelper_patElectronsNoIsoPF", nelectron)
stream.select("npatElectronHelper_selectedPatElectronsPF", nelectron1)
stream.select("npatElectron_patElectronsNoIsoPF", nelectron2)
stream.select("npatElectron_selectedPatElectronsPF", nelectron3)
stream.select("nrecoGenParticleHelperRA2b_genParticles", ngenparticlera2b)
stream.select("npatJetHelper_cleanPatJetsAK5Calo", njet)
stream.select("npatJetHelper_selectedPatJetsPF", njet1)
stream.select("npatJet_cleanPatJetsAK5Calo", njet2)
stream.select("npatJet_selectedPatJetsPF", njet3)
stream.select("npatMET_patMETsAK5Calo", nmet)
stream.select("npatMET_patMETsPF", nmet1)
stream.select("npatMuonHelper_patMuonsNoIsoPF", nmuon)
stream.select("npatMuonHelper_selectedPatMuonsPF", nmuon1)
stream.select("npatMuon_patMuonsNoIsoPF", nmuon2)
stream.select("npatMuon_selectedPatMuonsPF", nmuon3)
stream.select("npatTauHelper_selectedPatTausPF", ntau)
stream.select("npatTau_selectedPatTausPF", ntau1)
stream.select("nrecoVertex_offlinePrimaryVertices", nvertex)
stream.select("patTau_selectedPatTausPF.caloIso", tau1_caloIso)
stream.select("patTau_selectedPatTausPF.ecalIso", tau1_ecalIso)
stream.select("patTau_selectedPatTausPF.energy", tau1_energy)
stream.select("patTau_selectedPatTausPF.et", tau1_et)
stream.select("patTau_selectedPatTausPF.eta", tau1_eta)
stream.select("patTau_selectedPatTausPF.hcalIso", tau1_hcalIso)
stream.select("patTau_selectedPatTausPF.phi", tau1_phi)
stream.select("patTau_selectedPatTausPF.pt", tau1_pt)
stream.select("patTau_selectedPatTausPF.px", tau1_px)
stream.select("patTau_selectedPatTausPF.py", tau1_py)
stream.select("patTau_selectedPatTausPF.pz", tau1_pz)
stream.select("patTau_selectedPatTausPF.tauID_againstElectron", tau1_tauID_againstElectron)
stream.select("patTau_selectedPatTausPF.tauID_againstMuon", tau1_tauID_againstMuon)
stream.select("patTau_selectedPatTausPF.tauID_byIsolation", tau1_tauID_byIsolation)
stream.select("patTau_selectedPatTausPF.tauID_byTaNC", tau1_tauID_byTaNC)
stream.select("patTau_selectedPatTausPF.tauID_byTaNCfrHalfPercent", tau1_tauID_byTaNCfrHalfPercent)
stream.select("patTau_selectedPatTausPF.tauID_byTaNCfrQuarterPercent", tau1_tauID_byTaNCfrQuarterPercent)
stream.select("patTau_selectedPatTausPF.trackIso", tau1_trackIso)
stream.select("patTauHelper_selectedPatTausPF.genTauDecayModeID", tau_genTauDecayModeID)
stream.select("recoVertex_offlinePrimaryVertices.isFake", vertex_isFake)
stream.select("recoVertex_offlinePrimaryVertices.isValid", vertex_isValid)
stream.select("recoVertex_offlinePrimaryVertices.ndof", vertex_ndof)
stream.select("recoVertex_offlinePrimaryVertices.normalizedChi2", vertex_normalizedChi2)
stream.select("recoVertex_offlinePrimaryVertices.position_Rho", vertex_position_Rho)
stream.select("recoVertex_offlinePrimaryVertices.tracksSize", vertex_tracksSize)
stream.select("recoVertex_offlinePrimaryVertices.x", vertex_x)
stream.select("recoVertex_offlinePrimaryVertices.xError", vertex_xError)
stream.select("recoVertex_offlinePrimaryVertices.y", vertex_y)
stream.select("recoVertex_offlinePrimaryVertices.yError", vertex_yError)
stream.select("recoVertex_offlinePrimaryVertices.z", vertex_z)
stream.select("recoVertex_offlinePrimaryVertices.zError", vertex_zError)

