#include "TTree.h"
#include "TFile.h"
#include "TH1.h"
#include "TString.h"


void splitReducedTree() {
// Example of Root macro to copy a subset of a Tree to a new Tree
// Only selected entries are copied to the new Tree.
// The input file has been generated by the program in $ROOTSYS/test/Event
// with   Event 1000 1 99 1
//Author: Rene Brun

  TString oldfilestub= "/cu2/joshmt/mSUGRAdell/PART1/reducedTree.SSVHPT_PF2PATjets_JES0_JER0_PFMET_METunc0_PUunc0_BTagEff0_HLTEff0.";
  TString samplename="mSUGRA_tanb40_summer11_PART1";
  TString filename = oldfilestub+samplename;
  filename+=".root";

   //Get old file, old tree and set top branch address
  TFile *oldfile = new TFile(filename);
  TTree *oldtree = (TTree*) oldfile->Get("reducedTree");
  Long64_t nentries = oldtree->GetEntries();

   map<pair<int, int>, TH1D*> scanProcessTotalsMap;
   //load the histograms
   for (int i=0; i<oldfile->GetListOfKeys()->GetEntries(); i++) {
     TString objname=  oldfile->GetListOfKeys()->At(i)->GetName();
     if (objname.BeginsWith("scanProcessTotals") ) {
       TString m0str=   objname.Tokenize("_")->At(1)->GetName();
       TString m12str=   objname.Tokenize("_")->At(2)->GetName();
       int thism0 = m0str.Atoi();
       int thism12 = m12str.Atoi();
       scanProcessTotalsMap[make_pair(thism0,thism12)] = (TH1D*) oldfile->Get(objname);
     }
   }

   //stuff for getting values out of tree
   int m0,m12;
   oldtree->SetBranchAddress("m0",&m0);
   oldtree->SetBranchAddress("m12",&m12);

   map<pair<int,int>, TFile*> newfiles;
   map<pair<int,int>, TTree*> newtrees;
   //loop over the histograms to find out what points are in the tree
   for (map<pair<int, int>, TH1D*>::iterator iscanpoint = scanProcessTotalsMap.begin(); iscanpoint!=scanProcessTotalsMap.end(); ++iscanpoint) {

     TString histname=  (*iscanpoint)->GetName();


   }


   //Create a new file + a clone of old tree in new file
   TFile *newfile = new TFile("small.root","recreate");
   TTree *newtree = oldtree->CloneTree(0);

   for (Long64_t i=0;i<nentries; i++) {
      oldtree->GetEntry(i);
      if (event->GetNtrack() > 605) newtree->Fill();
      event->Clear();
   }
   newtree->Print();
   newtree->AutoSave();
   delete oldfile;

   delete newfile;
}
